#!/bin/bash
set -e
cd $(dirname $0)
nix build --print-build-logs --keep-failed

rm -f se4rs/main.generated.tex
if [ -f result/se4rs-main.tex ]; then
	cat <(echo -e "%%%%%%%%%%%%%%%%%%%%\n% This file is automatically generated. Refer to the markdown source.\n%%%%%%%%%%%%%%%%%%%%\n") result/se4rs-main.tex > se4rs/main.generated.tex
fi

rm -f se4rs/main.pdf
if [ -f result/se4rs-main.pdf ]; then
	cp result/se4rs-main.pdf se4rs/main.pdf
	chmod 644 se4rs/main.pdf
fi

unlink result
